feat: clicking entity location searches for github users matching that location
gitpoint/git-point pull request #802
Opened 2018-05-10 18:42 UTC by JSweet314

| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | iPhone 6/7, Samsung S8 |
| Bug fix?         | yes/**no**      |
| New feature?     | **yes**/no      |
| Includes tests?  | yes/**no**      |
| All Tests pass?  | **yes**/no      |
| Related ticket?  | # 640  |

---

## Screenshots

| Before   | After    |
| -------- | -------- |
|![before](https://image.ibb.co/hutpJy/Screen_Shot_2018_05_09_at_3_10_53_PM.png)|![after](https://image.ibb.co/kyJdBJ/Screen_Shot_2018_05_09_at_3_12_11_PM.png)|

## Description

Per the suggested solution, we changed the functionality of clicking on an entity's location to navigate to the search screen and initiate a search for users corresponding to the entity's location. This eliminates the need for the Communications.web method to direct the user outside of the application to google maps (deemed not very useful/interesting). Subsequently, we pass down the search query to the search screen from the navigation object's params to display the search term to the user in the RNSearchBar and MNSearchBar components. Rather than TabNavigator, an additional shared StackNavigator route was needed in order to allow for the passing of the params (upgrading the React-Navigation dependency to the current version would eliminate this need, however, that refactor would fall well outside the scope of this issue). You will note the new shared route titled 'SearchUsersByLocation' in the routes.js file. Navigating to this feature in this way also gives the user the added benefit of having a back arrow to return to the entity from which the location was derived.

2018-05-11 16:36 UTC, chinesedfan requested changes
Good teamwork! Left some comments for you. Feel free to tell me if you have different opinions.

2018-05-11 16:36 UTC, chinesedfan commented on routes.js
> +  SearchUsersByLocation: {
In order to share this screen for other places, I suggest to define it as `Search` and replace the one in `SearchStackNavigator` with `MainSearch`.

2018-05-11 16:36 UTC, chinesedfan commented on src/components/entity-info.component.js
> +            onPress={() => getUsersByLocation(entity.location, navigation)}
Let's write the implementation here directly. `getUsersByLocation` sounds like returning users but it is not.

2018-05-11 16:36 UTC, chinesedfan commented on src/search/screens/search.screen.js
> +      this.search(`location:${params.location}`, 1);
Please use `SearchTypes.USERS`, instead of `1`. And you'd better check `params && params.location`.

2018-05-11 16:36 UTC, chinesedfan commented on src/search/screens/search.screen.js
> +        isLocation = `location:${params.location}`;
`isLocation` usually means a boolean. How about naming it as `searchText`? And we can check in only one if statement, `if (params && params.location)`.

2018-05-11 16:36 UTC, chinesedfan commented on __tests__/tests/components/EntityInfo.js
> -    );
Try to test your new press action. Mock `navigation.navigate` and check whether it is called with right arguments.

2018-05-11 16:36 UTC, chinesedfan commented on android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.3-rc-2-all.zip
Is it really needed? If not, please do not commit, as well as several files like `Cound/Failed/project.pbxproj`.

2018-05-11 16:39 UTC, chinesedfan commented
> upgrading the React-Navigation dependency to the current version would eliminate this need, however, that refactor would fall well outside the scope of this issue

By the way, if it didn't introduce too much changes, maybe you can upgrading the dependency.

2018-05-14 07:42 UTC, machour requested changes
Hi @JSweet314! Thank you and other contributors for this PR 🎉 

Aside from what @chinesedfan already said, I left you a comment to further explain a little problem.

Also, I'm noticing two new empty files "Could" and "Failed" which shouldn't have been included in this PR. (joys of bash scripting, heh)

Don't hesitate to reach us on gitter if you need any help at all!

2018-05-14 07:42 UTC, machour commented on src/search/screens/search.screen.js
> +    if (params) {
We are already using navigation state in this screen to store/retrieve the searched keyword (see line 38 for example).
Here, it seems that as soon as there's a parameter, you assume that it's related to location, which seems wrong.

2026-09-22 16:05 UTC, closed without merging